---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: d8-kubevirt
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - Macvtap
      - HostDisk
  customizeComponents:
    patches:
    - resourceType: Deployment
      resourceName: virt-api
      patch: '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
    - resourceType: Deployment
      resourceName: virt-controller
      patch: '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
    - resourceType: DaemonSet
      resourceName: virt-handler
      patch: '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"deckhouse-registry"}]}}}}'
      type: strategic
  imagePullPolicy: IfNotPresent
  infra:
    replicas: 1
  workloadUpdateStrategy: {}
  imagePullPolicy: IfNotPresent
