{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmi-router
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vmi-router" "workload-resource-policy.deckhouse.io" "every-node")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: DaemonSet
    name: vmi-router
  updatePolicy:
    updateMode: "Auto"
{{- end }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: before-hook-creation
  name: vmi-router
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vmi-router" )) | nindent 2 }}
spec:
  {{- include "helm_lib_pdb_daemonset" . | nindent 2}}
  selector:
    matchLabels:
      app: vmi-router
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vmi-router
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "vmi-router" )) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: vmi-router
  template:
    metadata:
      labels:
        app: vmi-router
    spec:
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_root" . | nindent 6 }}
      imagePullSecrets:
        - name: deckhouse-registry
      serviceAccountName: vmi-router
      hostNetwork: true
      containers:
        - name: vmi-router
          args:
          - --db=/var/lib/kubevirt/vmi-router/routes.db
          - --cidr=10.10.10.0/24
          {{- include "helm_lib_module_container_security_context_privileged" . | nindent 10 }}
          image: {{ $.Values.global.modulesImages.registry }}:{{ $.Values.global.modulesImages.tags.kubevirt.vmiRouter }}
          imagePullPolicy: "IfNotPresent"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: data
              mountPath: /var/lib/kubevirt/vmi-router
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
      volumes:
        - name: data
          hostPath:
            path: /var/lib/kubevirt/vmi-router
            type: ""
